In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]])
myarr

array([[ 3,  6, 37,  7]])

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int32')

In [6]:
myarr[0,1]=45
myarr

array([[ 3, 45, 37,  7]])

In [10]:
listarray = np.array([[1,2,3],[4,5,6],[0,3,1]])
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,23,22})

array({34, 22, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(14)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [16]:
ispace = np.linspace(1,50,10)
ispace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
emp = np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34609111e-307, 1.33511018e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        9.34605716e-307, 1.37962456e-306, 1.42418172e-306],
       [8.06610070e-308, 6.89810244e-307, 1.22387550e-307,
        2.22522596e-306, 8.34423917e-308, 9.79107193e-307]])

In [18]:
emp_like = np.empty_like(ispace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [35]:
arr = np.array(99)
arr

array(99)

In [37]:
arr = arr.ravel()

In [38]:
arr.shape

(1,)

In [39]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0)

array([12,  8,  9])

In [41]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [42]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
ar.flat

In [44]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim

2

In [46]:
ar.size

9

In [47]:
ar.nbytes

36

In [49]:
one = np.array([1,2,3,4,634,2])
one

array([  1,   2,   3,   4, 634,   2])

In [50]:
one.argmax()

4

In [51]:
one.argmin()

0

In [52]:
one.argsort()

array([0, 1, 5, 2, 3, 4], dtype=int64)

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:
ar.argmin()

8

In [55]:
ar.argmax()

6

In [56]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [57]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [58]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [59]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [60]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [61]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [62]:
ar2 = np.array([[1,2,1],
                [8,5,12],
                [5,2,0]])
ar+ar2

array([[ 2,  4,  4],
       [12, 10, 18],
       [12,  3,  0]])

In [63]:
ar*ar2

array([[ 1,  4,  3],
       [32, 25, 72],
       [35,  2,  0]])

In [64]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [65]:
ar.sum()

29

In [66]:
ar.max()

7

In [67]:
ar.min()

0

In [68]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [70]:
type(np.where(ar>5))

tuple

In [71]:
np.count_nonzero(ar)

8

In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [73]:
ar[1,2]=0

In [74]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [79]:
import sys
py_ar = [0,4,55,2]
np_ar = np.array(py_ar)
sys.getsizeof (1)*len(py_ar)

112

In [80]:
np_ar.itemsize * np_ar.size

16

In [81]:
np_ar.tolist

<function ndarray.tolist>