In [1]:
import numpy as np


In [2]:
print(np.__version__)

1.24.3


In [3]:
l = [1,2,3,4,5,6,7,8,9]
x = np.array(l)
print(x)
print(type(x))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
print(x+5)
print(x-5)
print(x/5)
print(x*5)

[ 6  7  8  9 10 11 12 13 14]
[-4 -3 -2 -1  0  1  2  3  4]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]
[ 5 10 15 20 25 30 35 40 45]


In [5]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = a+b
print(c)

[ 7  9 11 13 15]


In [6]:
a = np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [7]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print(a.shape)

(2, 5)


In [8]:
a = np.array([[[1,2,3],[4,5,0]],
             [[6,7,8],[9,10,0]]])
print(a.shape)

(2, 2, 3)


In [9]:
np.zeros((3,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print(a.reshape(3,2))
print(a.reshape(1,6))
print(a.reshape(3,2))
print(a.reshape(6,1))

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2,3],
              [4,5,6]])
c = a+b
print(c)

[[ 2  4  6]
 [ 8 10 12]]


In [13]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7,8,9],
              [0,4,6]])
np.hstack((a,b))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 4, 6]])

In [14]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[1,2,3],
              [4,5,6]])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(np.random.rand(2,2))

[[0.99501898 0.58301866]
 [0.23870957 0.07028444]]


In [18]:
print(np.random.randint(0,10,size =[5,5]))

[[4 1 0 8 7]
 [7 9 0 5 7]
 [8 6 1 5 2]
 [8 8 6 8 8]
 [8 7 2 3 2]]


In [19]:
print(np.random.random())

0.651773394741912


In [20]:
print(np.random.random(size = [2,2]))

[[0.50953776 0.34445684]
 [0.42713087 0.81075585]]


In [21]:
print(np.random.choice(['a','e','i','o','u'],size =[ 10,4]))

[['o' 'e' 'e' 'u']
 ['a' 'i' 'i' 'a']
 ['a' 'e' 'i' 'a']
 ['a' 'a' 'e' 'i']
 ['i' 'a' 'u' 'a']
 ['o' 'u' 'o' 'a']
 ['u' 'i' 'a' 'u']
 ['a' 'o' 'o' 'i']
 ['e' 'o' 'i' 'e']
 ['o' 'o' 'o' 'e']]


In [22]:
print(np.random.choice(['a','e','i','o','u'],size = 10,p=[0.3,0.1,0.1,0.4,0.1]))

['o' 'o' 'a' 'o' 'a' 'u' 'a' 'e' 'a' 'o']


In [23]:
(np.random.randint(0,10,size =[5,5]))+1

array([[ 3,  5, 10,  9,  1],
       [10,  3,  8,  9,  2],
       [ 1,  5,  7, 10,  7],
       [10,  8,  5,  7,  8],
       [ 3,  1,  2,  8,  9]])

In [24]:
import numpy as np
a = np.array([132,134,167,189,876])
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))

132
876
299.6
288.9862280455593


In [25]:
import scipy.linalg as slin
a = np.array([[3,-5,8],
              [-1,2,3],
              [-5,-6,2]])
slin.det(a)

259.0

In [26]:
a = np.array([[3,-5,8],
              [-1,2,3],
              [-5,-6,2]])
np.trace(a)

7

In [27]:
import scipy.linalg as slin
a = np.array([[3,-5,8],
              [-1,2,3],
              [-5,-6,2]])
slin.inv(a)

array([[ 0.08494208, -0.14671815, -0.11969112],
       [-0.05019305,  0.17760618, -0.06563707],
       [ 0.06177606,  0.16602317,  0.003861  ]])

In [28]:
a = np.array([[3,-5,8],
              [-1,2,3],
              [-5,-6,2]])
np.transpose(a)

array([[ 3, -1, -5],
       [-5,  2, -6],
       [ 8,  3,  2]])

In [29]:
a = np.matrix([[3,-5,8],
              [-1,2,3],
              [-5,-6,2]])
b = np.matrix([[3],
               [4],
               [-41]])
print(a*b)

[[-339]
 [-118]
 [-121]]
